# Generated by Django 4.0.4 on 2022-05-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_iphone_nokia_others_redmi_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iphone',
            options={'verbose_name': 'iPhone', 'verbose_name_plural': 'iPhone Products'},
        ),
        migrations.AlterModelOptions(
            name='nokia',
            options={'verbose_name': 'Nokia', 'verbose_name_plural': 'Nokia Products'},
        ),
        migrations.AlterModelOptions(
            name='redmi',
            options={'verbose_name': 'Redmi', 'verbose_name_plural': 'Redmi Products'},
        ),
    ]
